### ISSUE TITLE
Preview image?

### ISSUE THREAD

**Issue by Kcko** [enzostvs/vue3-player-video#2]
Hi, ur component looks good :-)
Is possible to add "preview image" property? 

Im meaning what user see until the video starts playing.

**Comment by Kcko** [comment]
I solved it myself ;]

**Comment by enzostvs** [comment]
Hi !
Great ! I can add this feature this week if you want.
Thanks for your return :D

**Comment by Kcko** [comment]
Thx for fast reply. It is no needed, It was just only one property more ;-)
But thx for simple & effective component, Im learning VUE and this  helped me understand some other things ;-)
Keep up with good work.

Nice weekend.

**Comment by kurokh** [comment]
Hi!
Did you add this feature? I see the status on this issue is closed but don't see the prop for it.
Thanks for player!
